[theme]

# Primary accent for interactive elements
primaryColor = '#F6A429'

# Background color for the main content area
backgroundColor = '#202B3D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F6A429'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"