[theme]

# Primary accent for interactive elements
primaryColor = '#75BBA7'

# Background color for the main content area
backgroundColor = '#FFFCFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#75BBA7'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"